on: push
name: Deploy Lambdas
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  POSTGRES_URL: ${{ secrets.POSTGRES_URL }}

jobs:
  deploy-workspace:
    runs-on: ubuntu-latest
    run:
      working-directory: packages/lambdas/workspace
    steps:
      - uses: actions/checkout@master
      - name: install
        run: npm install
      - name: deploy
        run: npm run deploy
